services:
  mysql:
    image: mysql:8.0
    container_name: gamevault-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gamevault
      MYSQL_USER: gamevault
      MYSQL_PASSWORD: gamevault123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema/001_init.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./database/seeds/002_seed_data.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ugamevault", "-pgamevault123"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
